import './globals.css'
import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Stuff Sharing',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
